const jobType = Object.freeze({
  PG_DARKPOOL_WITHDRAW: 'PG_DARKPOOL_WITHDRAW',
  PG_DARKPOOL_UNISWAP_SINGLESWAP: 'PG_DARKPOOL_UNISWAP_SINGLESWAP',
  PG_DARKPOOL_UNISWAP_LP: 'PG_DARKPOOL_UNISWAP_LP',
  PG_DARKPOOL_UNISWAP_FEE_COLLECTING: 'PG_DARKPOOL_UNISWAP_FEE_COLLECTING',
  PG_DARKPOOL_UNISWAP_REMOVE_LIQUIDITY: 'PG_DARKPOOL_UNISWAP_REMOVE_LIQUIDITY',
  PG_DARKPOOL_CURVE_MULTI_EXCHANGE: 'PG_DARKPOOL_CURVE_MULTI_EXCHANGE',
  PG_DARKPOOL_CURVE_ADD_LIQUIDITY: 'PG_DARKPOOL_CURVE_ADD_LIQUIDITY',
  PG_DARKPOOL_CURVE_REMOVE_LIQUIDITY: 'PG_DARKPOOL_CURVE_REMOVE_LIQUIDITY',
})

const status = Object.freeze({
  QUEUED: 'QUEUED',
  ACCEPTED: 'ACCEPTED',
  SENT: 'SENT',
  MINED: 'MINED',
  RESUBMITTED: 'RESUBMITTED',
  CONFIRMED: 'CONFIRMED',
  FAILED: 'FAILED',
})

const curvePoolType = Object.freeze({
  PLAIN: 'PLAIN',
  LENDING: 'LENDING',
  META: 'META',
  CRYPTO: 'CRYPTO',
})

module.exports = {
  jobType,
  status,
  curvePoolType,
}  