const jobType = Object.freeze({
    PG_DARKPOOL_WITHDRAW: 'PG_DARKPOOL_WITHDRAW',
    PG_DARKPOOL_UNISWAP_SINGLESWAP: 'PG_DARKPOOL_UNISWAP_SINGLESWAP',
    PG_DARKPOOL_UNISWAP_LP: 'PG_DARKPOOL_UNISWAP_LP',
    PG_DARKPOOL_UNISWAP_FEE_COLLECTING: 'PG_DARKPOOL_UNISWAP_FEE_COLLECTING',
    PG_DARKPOOL_UNISWAP_REMOVE_LIQUIDITY: 'PG_DARKPOOL_UNISWAP_REMOVE_LIQUIDITY',
    PG_DARKPOOL_CURVE_EXCHANGE: 'PG_DARKPOOL_CURVE_EXCHANGE',
    PG_DARKPOOL_CURVE_LP: 'PG_DARKPOOL_CURVE_LP',
    PG_DARKPOOL_CURVE_REMOVE_LIQUIDITY: 'PG_DARKPOOL_CURVE_REMOVE_LIQUIDITY',
  })
  
  const status = Object.freeze({
    QUEUED: 'QUEUED',
    ACCEPTED: 'ACCEPTED',
    SENT: 'SENT',
    MINED: 'MINED',
    RESUBMITTED: 'RESUBMITTED',
    CONFIRMED: 'CONFIRMED',
    FAILED: 'FAILED',
  })
  
  module.exports = {
    jobType,
    status,
  }  